server:
  contextPath: ''
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driverClassName: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    initialSize: 5
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/cssbase?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    validationQuery: SELECT 1 FROM DUAL
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.css.cssbase.config.CustomEnumTypeHandler
  global-config:
    db-column-underline: true
    field-strategy: 0
    id-type: 0
    refresh-mapper: true
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.css.cssbase.moudles.user.entity
  type-handlers-package: com.css.cssbase.config

cssbase:
  shiro:
    excludeUrls: /sys/Login
