server:
  port: 8080
spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driverClassName: com.mysql.jdbc.Driver
    filters: stat,wall,slf4j
    initialSize: 5
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/cssbase?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    validationQuery: SELECT 1 FROM DUAL
  resources:
    static-locations: /statics
  #redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制。
      shutdown-timeout: 100ms
    password: ''
    port: 6379
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.css.cssbase.config.CustomEnumTypeHandler
  global-config:
    db-column-underline: true
    field-strategy: 0
    id-type: 0
    refresh-mapper: true
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.css.cssbase.moudles.user.entity
  type-handlers-package: com.css.cssbase.config

cssbase:
  shiro:
    excludeUrls: /sys/Login